[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "piano opera usual crush weapon two blush evolve earn screen auto execute young habit mango struggle life goat happy license rebuild play ancient there"
